### ISSUE TITLE
Remove space between plots on the distribution grid

### ISSUE THREAD

**Issue by hsauro** [sys-bio/teUtils#13]
The current distribution grid has large gaps between the plots (see first image), can we remove the gaps so that lit looks more like the second image, search google scatter matrix to see more examples. 

![image](https://user-images.githubusercontent.com/1054990/90171786-de04bd80-dd56-11ea-97f6-98311736f018.png)

![image](https://user-images.githubusercontent.com/1054990/90171772-d7764600-dd56-11ea-9493-58342941dfa2.png)

**Comment by joseph-hellerstein** [comment]
done
