### ISSUE TITLE
Add Alpha (transparency) as an option to plotParameterestiamtePairs

### ISSUE THREAD

**Issue by hsauro** [sys-bio/teUtils#14]
eg 

fitter.plotParameterEstimatePairs(['k1', 'k2'], markersize1=1, alpha=0.2)

![image](https://user-images.githubusercontent.com/1054990/90992282-7b37d100-e563-11ea-8c3f-7028e06cadaf.png)

**Comment by joseph-hellerstein** [comment]
Added alpha. Made options more flexible so can specify for plot and line in a plot.
