### ISSUE TITLE
More flexible way to do the generation of synthetic observations in boostrap

### ISSUE THREAD

**Issue by joseph-hellerstein** [sys-bio/teUtils#18]
A key part of bootstrap is creating synthetic observations on each iteration. The manner in which this done affects both the quality of the bootstrap result and computational efficiency. Create a new class, observationSynthesizer, that constructs synthetic observations and change bootstrap to have a keyword argument for an instance of observationSynthesizer.

**Comment by hsauro** [comment]
No applicable, code moved to sbstoat
