### ISSUE TITLE
ODE printing bug

### ISSUE THREAD

**Issue by VaninJoel** [sys-bio/teUtils#19]
Any of the odePrint return the same 'libsbml' is not defined. I checked the code, and it is used in the line [[122   self.doc = libsbml.readSBMLFromString (sbmlStr)](https://github.com/sys-bio/teUtils/blob/4d6086eb1b803ebbb37e0da0f9b83cb62ef6ec2e/teUtils/odePrint.py#L122)]
and it is defined at line [[13 #import tesbml as libsbml](https://github.com/sys-bio/teUtils/blob/4d6086eb1b803ebbb37e0da0f9b83cb62ef6ec2e/teUtils/odePrint.py#L13)], but it is commented out

<img width="362" alt="image" src="https://user-images.githubusercontent.com/34976329/196050506-f0dd4676-2d54-48d4-a1f4-e8efa6fc4415.png">

**Comment by hsauro** [comment]
Should be fixed in latest release

**Comment by hsauro** [comment]
Fixed in 2.9 and above
