### ISSUE TITLE
I needed a method to plot all fitted and observed data on one plot.

### ISSUE THREAD

**Issue by hsauro** [sys-bio/teUtils#8]
I needed a method to plot all fitted and observed data on one plot. I added this to my local copy

     def plotFitAll (self, figsize=None):
          import matplotlib.pyplot as plt
          plt.figure(figsize=figsize)
          for i in range (len (self.fitted_ts.values[0])-1):
              plt.plot (self.fitted_ts.values[:,0], self.fitted_ts.values[:,i+1])
          for i in range (len (self.observed_ts.values[0])-1):
              plt.scatter (self.observed_ts.values[:,0], self.observed_ts.values[:,i+1], marker='o')

I think it should work. You might want to do it differently to match your own way doing things however. I uploaded it to pypi

**Comment by joseph-hellerstein** [comment]
I have implemented this in the new version (a bit different code so that all plot options are available)
